[package]
name = "genetic_algorithm"
version = "0.1.0"
authors = ["Ângelo Rodem <angelorodem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr = "0.4.0"
rand = "0.8.3"